import styles from './soppa.module.css'
import Head from 'next/head'

const index = () => {
  return (
    <div className={styles.wrapper}>
       <Head>
          <title>Raw Food Recept | Soppor</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
       </Head>
      
      <h1>This is the soupe page</h1> 

    </div>
  )
}

export default index