import styles from '../../styles/pages.module.css'
import Head from 'next/head'
import { createClient } from 'contentful'
import RecipeCard from '../../components/recipeCard/RecipeCard'


export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY 
  })

  const res = await client.getEntries({content_type: 'soupes'})

  return {
    props: {
      soupes: res.items
    }
  }
}

const index = ({soupes}) => {

  return (
    <div className={styles.wrapper}>
       <Head>
          <title>Raw Food Recept | Soppor</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
       </Head>
     
        <div>
          {soupes.map(soupe => (
            <RecipeCard key={soupe.sys.id} soupe={soupe}/>
          ))}
        </div>
      
      
     
      
    </div>
  )
}



export default index