import styles from '../../styles/pages.module.css'
import Head from 'next/head'
import { client } from '../../graphql/apolloClient'
import { getSoupsQuery } from '../../graphql/pages'
import Link from 'next/link'





const index = ({data}) => {


console.log(data)


  return (
    <div className={styles.wrapper}>
       <Head>
          <title>Raw Food Recept | Soppor</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
       </Head>
      {data.map(item => (
        <div className={styles.card}key={item.title}>
          <img src={item.imageLink} alt={item.title}  className={styles.img} />
          <p className={styles.title}>{item.title}</p>
          <Link href={"/soppor/" + item.slug}><div className={styles.button}>Recept</div></Link>
          <div className={styles.gradient}></div>
         
        </div>
      ))}
      
     
      
    </div>
  )
}

export const getServerSideProps = async () => {

  const {
    data, error
  } = await client.query({
    query: getSoupsQuery()
  })



 console.log(data)
  return {
    props: {
      data: data.soupsCollection.items
  }}
}

export default index