import Head from 'next/head'
import Carousel from '../components/carousel/Carousel'
import HomeText from '../components/homeText/HomeText'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Raw Food Recept | Hem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div>
        <h1>Raw food</h1>
        <Carousel/>   
        <HomeText/>  
      </div>

        
    </div>
  )
}
